service: localstack-demo

plugins:
  - serverless-localstack

custom:
  localstack:
    debug: true
    stages:
      - local
    endpointFile: localstack_endpoints.json
    lambda:
      # Enable this flag to improve performance
      mountCode: src # specify either "true", or a relative path to the root Lambda mount path

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/index.hello
